# Generated by Django 3.0.7 on 2021-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210419_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='size',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
