# Generated by Django 3.0.7 on 2021-04-27 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_remove_messagemodel_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='friends',
            new_name='friend',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
