# Generated by Django 3.0.7 on 2021-05-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='socket_connection',
            field=models.IntegerField(default=0),
        ),
    ]
